spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/stockradar?&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create

  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: 61BIKafJ6sanuOYN5jO0
            client-secret: 75boCh3TOv
            client-name: Naver
            scope:
              - name
              - email
            redirect-uri: "http://localhost:8080/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic

          discord:
            client-id: 1344515894562525327
            client-secret: dDE-fXMkTeAvFvIblXKk1Ge97TgwmF_2
            client-name: Discord
            scope:
              - identify
              - email
            redirect-uri: "http://localhost:8080/login/oauth2/code/discord"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic

          google:
            client-id: 414865344395-0caj9lnpke45agppft8o04q2kpi7je50.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
            client-name: Google
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          discord:
            authorization-uri: https://discord.com/oauth2/authorize
            token-uri: https://discord.com/api/oauth2/token
            user-info-uri: https://discord.com/api/users/@me
            user-name-attribute: id

jwt:
  secret: "nJqBg/I14BcNecIsAsdWXwQa4E6fC20rXpHxb0EcHlE="


elasticsearch:
  host: localhost:9200
  username: #fill out
  password: #fill out

cloud:
  aws:
    s3:
      bucket: #fill out
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: # fill out
      secretKey: # fill out